# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20160806_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='date',
            field=models.CharField(default=b'99 Dec, 9999', max_length=50),
        ),
    ]
