# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_detail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='site_name',
            field=models.CharField(default=b'zzzz', max_length=50),
        ),
    ]
